# Generated by Django 4.2.1 on 2023-05-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birthday',
            field=models.TextField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='mbti',
            field=models.TextField(max_length=10, null=True),
        ),
    ]
